name: Prod - Deploy to Heroku
on: workflow_dispatch

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'autonomo-web-prod'
          heroku_email: 'me@pabloibanez.com'
        env:
          HD_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
